import { type NextPage } from "next";
import Head from "next/head";

import { PlacesProvider } from "~/utils/usePlaces";
import HomeLayout from "~/ui/home/layout";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PlacesProvider>
        <HomeLayout />
      </PlacesProvider>
    </>
  );
};

export default Home;
